apiVersion: v1
kind: Service
metadata:
  name: bookings
  labels:
    name: bookings-service
    app: movie-booking-app
spec:
  type: NodePort
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30003
  selector:
    name: bookings-pod
    app: movie-booking-app