apiVersion: v1
kind: Service
metadata:
  name: movies
  labels:
    name: movies-service
    app: movie-booking-app
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
  selector:
    name: movies-pod
    app: movie-booking-app