apiVersion: v1
kind: Service
metadata:
  name: showtimes
  labels:
    name: showtimes-service
    app: movie-booking-app
spec:
  type: NodePort
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30002
  selector:
    name: showtimes-pod
    app: movie-booking-app