apiVersion: v1
kind: Pod
metadata:
  name: bookings-pod
  labels:
    name: bookings-pod
    app: movie-booking-app
spec:
  containers:
    - name: bookings
      image: moviebookingapp_bookings
      imagePullPolicy: Never
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 5003