apiVersion: v1
kind: Pod
metadata:
  name: movies-pod
  labels:
    name: movies-pod
    app: movie-booking-app
spec:
  containers:
    - name: movies
      image: moviebookingapp_movies
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 5001