apiVersion: v1
kind: Pod
metadata:
  name: showtimes-pod
  labels:
    name: showtimes-pod
    app: movie-booking-app
spec:
  containers:
    - name: showtimes
      image: moviebookingapp_showtimes
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 5002