apiVersion: v1
kind: Pod
metadata:
  name: user-pod
  labels:
    name: user-pod
    app: user-booking-app
spec:
  containers:
    - name: user
      image: moviebookingapp_user
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 5000