apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user-service
    app: movie-booking-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    name: user-pod
    app: movie-booking-app